title: Fast Coder
description: Fast coder software development blog.
author: Deivydas Voroneckis
avatar: /logo.jpg
email: v.deivydas2@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: DVoroneckis
  card: summary
logo: logo.png
social:
  name: Deivydas Voroneckis
  links:
    - https://twitter.com/DVoroneckis
    - https://www.facebook.com/deivydas.voroneckis
    - https://github.com/deivyd321
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en

url: 'https://deivyd321.github.io/notes'
baseurl: '/notes'

skin:
    midnight